<?php
// +----------------------------------------------------------------------
// | QULINKE [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2020 EBACERA All rights reserved.
// +----------------------------------------------------------------------
// | Author: 重设人生 <573914456@qq.com>
// | Date:  2023/6/18 16:32
// +----------------------------------------------------------------------

namespace KenCore\Model;

use KenCore\Scope\isDeleteScope;
use KenCore\Traits\Error;
use KenCore\Traits\ModelMacroTrait;
use Hyperf\DbConnection\Model\Model;
use Hyperf\ModelCache\Cacheable;
use Hyperf\ModelCache\CacheableInterface;

/**
 *
 */
abstract class AbstractModel extends Model implements CacheableInterface
{

    //是否使用软删除
    //use SoftDeletes;
    use Cacheable,ModelMacroTrait;

    use Error;

    //时间字段已int类型存储
    protected $dateFormat = 'U';

    const CREATED_AT = 'create_time';

    const UPDATED_AT = 'update_time';

    protected $appends = [
        'format_time'
    ];

    //protected $hidden = ['create_time', 'update_time'];

    /**
     * Notes: 格式化时间戳
     * Author: 重设人生 <573914456@qq.com>
     * DataTime: 2021/9/3 6:10
     * @return false|string
     */
    protected function getFormatTimeAttribute()
    {
        return $this->create_time && $this->create_time->getTimestamp() > 0 ? date('Y-m-d H:i:s',
            $this->create_time->getTimestamp()) : '--';
    }


    /**
     * Notes: 过滤软删除 is_delete
     * Author: 重设人生 <573914456@qq.com>
     * DataTime: 2022/10/9 16:42
     */
    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new isDeleteScope());
    }

}
